<?php
declare(strict_types=1);

namespace SixShop\Core\Service;

use Composer\InstalledVersions;
use Composer\Json\JsonFile;
use SixShop\Core\Exception\ExceptionHandle;
use SixShop\Core\Plugin;
use SixShop\Core\Request;
use think\event\HttpRun;
use think\exception\Handle;
use think\Service;

class CoreService extends Service
{
    public static string $extensionPath;

    public static array $extensionComposerMap = [];

    /* @deprecated */
    public static array $extensionNameList = [];

    public function register(): void
    {
        $this->app->bind(Handle::class, ExceptionHandle::class);
        $this->app->bind('think\Request', Request::class);
        $this->app->bind('classLoader',
            require $this->app->getRootPath() . 'vendor/autoload.php');
        self::$extensionPath = $this->app->getRootPath() . 'extension' . DIRECTORY_SEPARATOR;
        $this->initExtensionList();
        $this->compatibleExtensNameList();
    }

    public function boot(): void
    {
        $this->app->make(AutoloadService::class)->init($this->app);
        $this->app->make(HookAttributeService::class)->init($this->app);
        $this->app->event->listen(HttpRun::class, function () {
            $this->registerRoutes($this->app->make(RegisterRouteService::class)->init($this->app));
        });

        $this->app->make(CommandService::class)->init($this->app, function ($commands) {
            $this->commands($commands);
        });
    }

    private function initExtensionList(): void
    {
        if (!empty(self::$extensionComposerMap)) {
            return;
        }
        $extensionComposerFile = $this->app->getRootPath() . 'runtime/extension_' . InstalledVersions::getRootPackage()['reference'].'.php';
        if (file_exists($extensionComposerFile)) {
            self::$extensionComposerMap = require $extensionComposerFile;
            return;
        }
        foreach (InstalledVersions::getInstalledPackagesByType(Plugin::EXTENSION_TYPE) as $item) {
            $version = InstalledVersions::getInstallPath($item);
            $installPath = InstalledVersions::getInstallPath($item);
            $composerJson = new JsonFile($installPath . '/composer.json');
            $composer = $composerJson->read();
            self::$extensionComposerMap[$composer['extra']['sixshop']['id']] = $composer;
        };
        $header = '// This file is automatically generated at:' . date('Y-m-d H:i:s') . PHP_EOL . 'declare (strict_types = 1);' . PHP_EOL;
        $content = '<?php ' . PHP_EOL . $header . "return " . var_export(self::$extensionComposerMap, true) . ';';
        file_put_contents($extensionComposerFile, $content);
    }

    /* @deprecated */
    private function compatibleExtensNameList(): void
    {
        if (empty(self::$extensionNameList)) {
            self::$extensionNameList = array_keys(self::$extensionComposerMap);
            $normalFile = $this->app->getRootPath() . 'runtime/module_name_list_normal.php';
            if (file_exists($normalFile)) {
                self::$extensionNameList = array_merge(self::$extensionNameList, require $normalFile);
            }
        }
    }
}